version: "3"
services:
  mitmproxy:
    build:
      dockerfile: ./config/mitmproxy/Dockerfile
      context: .
    tty: true
    ports: 
      - 8080:8080
      - 8081:8081
    command: ["mitmweb", "--mode", "upstream:torproxy:5566"]
    links: 
      - torproxy:torproxy
  torproxy:
    image: mattes/rotating-proxy:latest
    volumes: 
      - ./config/tor/tor.conf:/etc/tor/torrc
    ports: 
      - 5566:5566
      - 4444:4444
    environment: 
      - tors=4
